mex getRgDcLuster.cpp pProces.cpp cMath.cpp detect.cpp gFK.cpp kMusic.cpp ...
    eigR.cpp music.cpp memAlocFree.cpp myRdrClusters.cpp ...
    linDataSeg.cpp rdWrite.cpp saveDataFiles.cpp processRdrBlocks.cpp