/*COEFFIECIENTS OF NARROW BANDPASS FILTER
*/
#include "math.h"
#include "mex.h"   /* This one is required */
double** myAlloc2(int, int);
double* myAlloc(int);
void myFree2(double**, int);
//double rotateUla(double, double);
//int* rotateAndExtract(double**, double*, int, int);
//int rotationMatch(double*, int, int*, double*); 
double* rotateDecode(double**, int, int, int*);
double* stateDecode(double**, int, int, int*);

void Usage()
{
    printf(" Updated on 10th Apr 2025 at Princeton NJ for Book 5th Chapter\n");
    printf(" Note matlab component is generated by using\n");
    printf(" validPhi = stateDecode(doa3, D, ula, &kt); at line  53 in ula3doaStf.cpp\n");
    printf(" OR\n");
    printf(" validPhi = rotateDecode(doa3, D, ula, &kt); at line 52 in ula3doaStf.cpp\n");
    printf(" renamed as map3ulaS.mexw64; or map3ulaR.mexw64; or simply map3ula.mexw64\n");
    printf(" [theta ulaPks] = map3ula(a,b,c);\n");
    printf(" Inputs: 3\n");
    printf(" 1. a,b,c are row vectors of peak DOA angles of each ULA\n");
    printf(" Outputs: 2\n");
    printf(" 1. theta estimated from 3 angles for D targets\n");
    printf(" 2. ULA peaks at A B C\n");
    return;
}

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    double* inputA,*inputB,*inputC;
    double* thetaPtr,*doa3Ptr,**doa3;
	int k,m,c,D,ula,kt,zone,*tgtIndx,er;
    double *validPhi,*estPhi;

    

    if ((nlhs != 2) || (nrhs != 3))
    {
        printf(" Usage Error Parameters Left Hand Side = %d(2) .. Right Hand Side = %d(3) \n", nlhs, nrhs);
        Usage(); return;
    }

    // par 1
    if (mxGetM(prhs[0]) != 1)
    {
        Usage();
        printf(" prhs[0] r is  not a row vector try transpose\n");
        return;
    }
    c = mxGetN(prhs[0]);
    inputA = mxGetPr(prhs[0]);

    // par 2
    if (mxGetM(prhs[1]) != 1)
    {
        Usage();
        printf(" prhs[1] r is  not a row vector try transpose\n");
        return;
    }
    c = mxGetN(prhs[1]);
    inputB = mxGetPr(prhs[1]);

    // par 3
    if (mxGetM(prhs[2]) != 1)
    {
        Usage();
        printf(" prhs[2] r is  not a row vector try transpose\n");
        return;
    }
    c = mxGetN(prhs[2]);
    inputC = mxGetPr(prhs[2]);
    D = c; ula = 3;
    doa3 = myAlloc2(ula, D); //validPhi = myAlloc(D);

    for (k = 0; k < D; k++)
    {
        doa3[0][k] = inputA[k];
        doa3[1][k] = inputB[k];
        doa3[2][k] = inputC[k];
    }
  
    validPhi = rotateDecode(doa3, D, ula, &kt);
    //validPhi = stateDecode(doa3, D, ula, &kt);

    plhs[0] = mxCreateDoubleMatrix(1, D, mxREAL);
	thetaPtr = mxGetPr(plhs[0]);

    for (k = 0; k < D; k++)
    {
        thetaPtr[k] = validPhi[k];
    }

    plhs[1] = mxCreateDoubleMatrix(ula, D, mxREAL);
    doa3Ptr = mxGetPr(plhs[1]);
    for (m = 0; m < ula; m++)
    {
        for (k = 0; k < D; k++)
        {
            doa3Ptr[k * ula + m] = doa3[m][k];
        }
    }

    myFree2(doa3, ula);
	
    return;
}

    