#include "math.h"
#include "mex.h"   /* This one is required */
#include "memAlocFree.h"
void Usage();
//double** stfDoa(double**, double, double, int, int, double*, int, double**);
double** ula3doa(double**, double**, double**, double, double, int, int, double*, int, double**);

void Usage()
{
    printf(" Updated on 10th Apr 2025 at Princeton NJ for Book 5th Chapter\n");
    printf(" Note matlab component is generated by using\n");
    printf(" validPhi = stateDecode(doa3, D, ula, &kt); at line  53 in ula3doaStf.cpp\n");
    printf(" OR\n");
    printf(" validPhi = rotateDecode(doa3, D, ula, &kt); at line 52 in ula3doaStf.cpp\n");

    printf(" [Jk theta doa] = stfSweepDoa(Ha,Hb,Hc,r,dbl,kmax,SE,D);\n");
    printf(" Inputs: 8\n");
    printf("1. Ha,Hb,Hc covariance Matrix m by m\n");
    printf("4. r is pole position of NBP filter .\n");
    printf("5. dbl is the ratio of distance between any two sensors and wavelenth \n");
    printf("6. kmax is the length of Jk\n");
    printf("7. SE is two array SE[0] start SE[1] end in degrees 5 to 88\n");
    printf("8. D is the number of emitters\n");
    printf(" Outputs: 3\n");
    printf("1. Jk 3 columns A,B,C is the spectrum of length kmax\n");
    printf("2. theta is the sweep of length kmax\n");
    printf("3. doa is D by 2 matrix\n");
    return;
}



void mexFunction(int nlhs, mxArray* plhs[], int nrhs, const mxArray* prhs[])
{
    double* inputR, * inputH, * inputDbyL, * inputKmax, *inputSE,*inputD;
    double* JkPtr,*doaPtr,*thetaPtr;

    int rcH[2];
    double** Ha,** Hb,** Hc, **Jk3Theta, ** doa3stf;
    int i, j, m,k,kmax,D,rows,cols;
    double r, d_by_lambda;
    double* w, *doa,*Jk,se[2];


    if ((nlhs != 3) || (nrhs != 8))
    {
        printf(" Usage Error Parameters Left Hand Side = %d(3) .. Right Hand Side = %d(8) \n", nlhs, nrhs);
        Usage(); return;
    }


    for (k = 0; k < 3; k++)
    {
        if (mxGetM(prhs[k]) != mxGetN(prhs[k]))
        {
            Usage(); mexErrMsgTxt(" input must be a square matrix \n"); return; 
        }
        else
        {
            m = mxGetM(prhs[k]);
            if (m < 2) { Usage(); mexErrMsgTxt(" input cannot be a scalar\n"); return; }
        }
    }

    // par 1 Ha matrix
    inputH = mxGetPr(prhs[0]); rcH[0] = m; rcH[1] = m;
    printf(" size of covarinace matrix %d\n", m);
    Ha = myAlloc2(m, m);
    for (m = 0; m < rcH[0]; m++)
    {
        for (k = 0; k < rcH[1]; k++)
        {
            Ha[m][k] = inputH[k * rcH[0] + m];
        }
    }

    // par 2 Hb matrix
    inputH = mxGetPr(prhs[1]); rcH[0] = m; rcH[1] = m;
    printf(" size of covarinace matrix %d\n", m);
    Hb = myAlloc2(m, m);
    for (m = 0; m < rcH[0]; m++)
    {
        for (k = 0; k < rcH[1]; k++)
        {
            Hb[m][k] = inputH[k * rcH[0] + m];
        }
    }

    // par 3 Hc matrix
    inputH = mxGetPr(prhs[2]); rcH[0] = m; rcH[1] = m;
    printf(" size of covarinace matrix %d\n", m);
    Hc = myAlloc2(m, m);
    for (m = 0; m < rcH[0]; m++)
    {
        for (k = 0; k < rcH[1]; k++)
        {
            Hc[m][k] = inputH[k * rcH[0] + m];
        }
    }


    // par 4 r
    if ((mxGetM(prhs[3]) != 1) || (mxGetN(prhs[3]) != 1))
    {
        Usage();
        printf("prhs[3] theta is not a scalar.\n");
        return;
    }
    inputR = mxGetPr(prhs[3]);
    r = inputR[0];

    // par 5 dbyl
    if ((mxGetM(prhs[4]) != 1) || (mxGetN(prhs[4]) != 1))
    {
        Usage();
        printf("prhs[4] dbyl is not a scalar.\n");
        return;
    }
    inputDbyL = mxGetPr(prhs[4]);
    d_by_lambda = inputDbyL[0];

    // par 6 kmax
    if ((mxGetM(prhs[5]) != 1) || (mxGetN(prhs[5]) != 1))
    {
        Usage();
        printf("prhs[5] m is not a scalar.\n");
        return;
    }
    inputKmax = mxGetPr(prhs[5]);
    kmax = inputKmax[0];

    // par 7 start and end
    if ((mxGetM(prhs[6]) != 1) || (mxGetN(prhs[6]) != 2))
    {
        Usage();
        printf("prhs[6] m is not a two vector\n");
        return;
    }
    inputSE = mxGetPr(prhs[6]);
    se[0] = inputSE[0]; se[1] = inputSE[1];

    // par 8 kmax
    if ((mxGetM(prhs[7]) != 1) || (mxGetN(prhs[7]) != 1))
    {
        Usage();
        printf("prhs[7] D is not a scalar.\n");
        return;
    }
    inputD = mxGetPr(prhs[7]);
    D = inputD[0];

    doa3stf = myAlloc2(6,D);

    printf("D = %d r = %3.4f dbl %3.4f and kmax %d [%3.4f %3.4f] \n",D, r, d_by_lambda,kmax,se[0], se[1]);
    //JkTheta = stfDoa(H, r, d_by_lambda, m, D, se, kmax, doaStf);
    Jk3Theta = ula3doa(Ha, Hb, Hc, r, d_by_lambda, m, D, se, kmax, doa3stf);

 
    /* allocations and initializations */


    plhs[0] = mxCreateDoubleMatrix(3, kmax, mxREAL);
    JkPtr =  mxGetPr(plhs[0]);
    plhs[1] = mxCreateDoubleMatrix(1, kmax, mxREAL);
    thetaPtr = mxGetPr(plhs[1]);
    plhs[2] = mxCreateDoubleMatrix(6, D, mxREAL);
    doaPtr = mxGetPr(plhs[2]);

    rows = 3; cols = kmax;
    /* create and return matrix */
    for (k = 0; k < 3; k++)
    {
        for (i = 0; i < kmax; i++) JkPtr[i * rows + k] = Jk3Theta[k][i];
    }

    for (i = 0; i < kmax; i++) thetaPtr[i] = Jk3Theta[3][i];

    rows = 6; cols = D;
    for (m = 0; m < rows; m++)
    {
        for (k = 0; k < cols; k++)
        {
            doaPtr[k * rows + m] = doa3stf[m][k];
        }
    }

    return;
}

