function add_signature()
    text(0.98, 0.02, 'Dr Kaluri', 'Units', 'normalized', ...
         'HorizontalAlignment', 'right', 'VerticalAlignment', 'bottom', ...
         'FontSize', 6, 'Color', [0.5 0.5 0.5]);
end